version: 2
updates:
  # Update GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"


  # Update NuGet packages
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"

    # https://docs.github.com/en/code-security/how-tos/secure-your-supply-chain/manage-your-dependency-security/controlling-dependencies-updated#allowing-specific-dependencies-to-be-updated
    allow:
      # the allow key is needed so that the ignore key below works
      - dependency-type: "all"
    ignore:
      - dependency-name: "FSharp.Core"
      - dependency-name: "RhinoCommon"
      - dependency-name: "Eto.Forms"





